//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int rollno { get; set; }
        public int @class { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public int amt { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
